// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ce30d3a2-f6c6-441a-b434-50c147f92e82",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_a8IvzYEes",
    "aws_user_pools_web_client_id": "3qtmaah8hlnqhfhusn6u3jmka",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://p2rt5j4ahraifpiwpihocfcgme.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-j2wh5qzkbvdebizwwvoy3oaqxq",
    "aws_content_delivery_bucket": "myapp-20200216164951-hostingbucket-test",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://myapp-20200216164951-hostingbucket-test.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
